// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`



declare namespace Cloudflare {
        interface Env {
                DB: D1Database;
        }
}
interface Env extends Cloudflare.Env {}
